-- ============================================================
-- AI-Based OS Algorithm Simulator + Recommendation Engine
-- Database Schema (ORACLE VERSION)
-- Covers: CPU Scheduling, Memory Management, Disk Scheduling,
-- Deadlock Detection, and the self-generated AI training pipeline
--
-- Run this in SQL Command Line (sqlplus) or SQL Developer,
-- connected to your own schema/user (not as SYS).
-- ============================================================

-- ------------------------------------------------------------
-- 1. USERS
-- ------------------------------------------------------------
CREATE TABLE users (
    user_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    roll_no     VARCHAR2(30)  NOT NULL UNIQUE,
    email       VARCHAR2(120) NOT NULL UNIQUE,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- ------------------------------------------------------------
-- 2. SIMULATIONS (parent table for every run, of any module)
-- ------------------------------------------------------------
CREATE TABLE simulations (
    sim_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER NOT NULL,
    module_type VARCHAR2(10) NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_sim_user FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_module_type CHECK (module_type IN ('cpu','memory','disk','deadlock'))
);

-- ============================================================
-- MODULE 1: CPU SCHEDULING
-- Algorithms: FCFS, SJF, SRTF, Round Robin
-- ============================================================

CREATE TABLE cpu_processes (
    process_row_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sim_id          NUMBER NOT NULL,
    process_label   VARCHAR2(20) NOT NULL,
    arrival_time    NUMBER NOT NULL,
    burst_time      NUMBER NOT NULL,
    priority        NUMBER DEFAULT NULL,
    CONSTRAINT fk_cpuproc_sim FOREIGN KEY (sim_id) REFERENCES simulations(sim_id)
        ON DELETE CASCADE
);

CREATE TABLE cpu_inputs (
    input_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sim_id              NUMBER NOT NULL,
    process_count       NUMBER NOT NULL,
    avg_burst_time      FLOAT NOT NULL,
    burst_time_variance FLOAT NOT NULL,
    avg_arrival_gap     FLOAT NOT NULL,
    time_quantum        NUMBER DEFAULT NULL,
    CONSTRAINT fk_cpuin_sim FOREIGN KEY (sim_id) REFERENCES simulations(sim_id)
        ON DELETE CASCADE
);

CREATE TABLE cpu_results (
    result_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sim_id               NUMBER NOT NULL,
    algorithm            VARCHAR2(20) NOT NULL,
    avg_waiting_time     FLOAT NOT NULL,
    avg_turnaround_time  FLOAT NOT NULL,
    context_switches     NUMBER DEFAULT 0,
    gantt_chart_json      CLOB,
    CONSTRAINT fk_cpures_sim FOREIGN KEY (sim_id) REFERENCES simulations(sim_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_cpu_algo CHECK (algorithm IN ('FCFS','SJF','SRTF','ROUND_ROBIN'))
);

-- ============================================================
-- MODULE 2: MEMORY MANAGEMENT / PAGE REPLACEMENT
-- Algorithms: FIFO, LRU, Optimal
-- ============================================================

CREATE TABLE memory_inputs (
    input_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sim_id              NUMBER NOT NULL,
    reference_string    VARCHAR2(255) NOT NULL,
    reference_length    NUMBER NOT NULL,
    frame_count         NUMBER NOT NULL,
    unique_pages        NUMBER NOT NULL,
    CONSTRAINT fk_memin_sim FOREIGN KEY (sim_id) REFERENCES simulations(sim_id)
        ON DELETE CASCADE
);

CREATE TABLE memory_results (
    result_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sim_id           NUMBER NOT NULL,
    algorithm        VARCHAR2(10) NOT NULL,
    page_faults      NUMBER NOT NULL,
    page_hits        NUMBER NOT NULL,
    hit_miss_trace   CLOB,
    CONSTRAINT fk_memres_sim FOREIGN KEY (sim_id) REFERENCES simulations(sim_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_mem_algo CHECK (algorithm IN ('FIFO','LRU','OPTIMAL'))
);

-- ============================================================
-- MODULE 3: DISK SCHEDULING
-- Algorithms: FCFS, SSTF, SCAN / C-SCAN
-- ============================================================

CREATE TABLE disk_inputs (
    input_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sim_id              NUMBER NOT NULL,
    request_queue       VARCHAR2(255) NOT NULL,
    request_count       NUMBER NOT NULL,
    starting_head       NUMBER NOT NULL,
    disk_size           NUMBER DEFAULT 200,
    direction            VARCHAR2(10) DEFAULT NULL,
    CONSTRAINT fk_diskin_sim FOREIGN KEY (sim_id) REFERENCES simulations(sim_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_disk_dir CHECK (direction IN ('LEFT','RIGHT') OR direction IS NULL)
);

CREATE TABLE disk_results (
    result_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sim_id                NUMBER NOT NULL,
    algorithm             VARCHAR2(10) NOT NULL,
    total_head_movement   NUMBER NOT NULL,
    service_order          CLOB NOT NULL,
    CONSTRAINT fk_diskres_sim FOREIGN KEY (sim_id) REFERENCES simulations(sim_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_disk_algo CHECK (algorithm IN ('FCFS','SSTF','SCAN','C_SCAN'))
);

-- ============================================================
-- MODULE 4: DEADLOCK DETECTION / BANKER'S ALGORITHM
-- ============================================================

CREATE TABLE deadlock_inputs (
    input_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sim_id           NUMBER NOT NULL,
    process_count    NUMBER NOT NULL,
    resource_count   NUMBER NOT NULL,
    allocation_matrix CLOB NOT NULL,
    max_matrix        CLOB NOT NULL,
    available_vector  VARCHAR2(255) NOT NULL,
    CONSTRAINT fk_dlin_sim FOREIGN KEY (sim_id) REFERENCES simulations(sim_id)
        ON DELETE CASCADE
);

CREATE TABLE deadlock_results (
    result_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sim_id           NUMBER NOT NULL,
    is_safe          NUMBER(1) NOT NULL,   -- 1 = safe, 0 = unsafe (Oracle has no BOOLEAN in tables pre-23c)
    safe_sequence    VARCHAR2(255),
    deadlocked_processes VARCHAR2(255),
    CONSTRAINT fk_dlres_sim FOREIGN KEY (sim_id) REFERENCES simulations(sim_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_is_safe CHECK (is_safe IN (0,1))
);

-- ============================================================
-- AI TRAINING + RECOMMENDATION PIPELINE
-- ============================================================

CREATE TABLE training_dataset (
    record_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sim_id               NUMBER NOT NULL,
    module_type          VARCHAR2(10) NOT NULL,
    process_count        NUMBER DEFAULT NULL,
    avg_burst_time        FLOAT DEFAULT NULL,
    burst_time_variance   FLOAT DEFAULT NULL,
    frame_count           NUMBER DEFAULT NULL,
    unique_pages          NUMBER DEFAULT NULL,
    request_count         NUMBER DEFAULT NULL,
    best_algorithm        VARCHAR2(30) NOT NULL,
    best_metric_value      FLOAT NOT NULL,
    CONSTRAINT fk_train_sim FOREIGN KEY (sim_id) REFERENCES simulations(sim_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_train_module CHECK (module_type IN ('cpu','memory','disk','deadlock'))
);

CREATE TABLE ai_recommendations (
    rec_id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sim_id                 NUMBER NOT NULL,
    recommended_algorithm   VARCHAR2(30) NOT NULL,
    confidence_score        FLOAT NOT NULL,
    explanation_text         CLOB NOT NULL,
    model_version            VARCHAR2(20) DEFAULT 'v1',
    created_at               TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_rec_sim FOREIGN KEY (sim_id) REFERENCES simulations(sim_id)
        ON DELETE CASCADE
);

-- ============================================================
-- USEFUL SAMPLE QUERIES (for viva / DBMS demonstration)
-- ============================================================

-- Every simulation a user ran, with recommended vs actual best algorithm
-- SELECT u.name, s.module_type, s.created_at,
--        ar.recommended_algorithm, td.best_algorithm AS actual_best
-- FROM users u
-- JOIN simulations s   ON u.user_id = s.user_id
-- JOIN ai_recommendations ar ON s.sim_id = ar.sim_id
-- JOIN training_dataset td   ON s.sim_id = td.sim_id
-- ORDER BY s.created_at DESC;

-- Accuracy of the recommendation engine so far
-- SELECT
--   COUNT(*) AS total,
--   SUM(CASE WHEN ar.recommended_algorithm = td.best_algorithm THEN 1 ELSE 0 END) AS correct_matches
-- FROM ai_recommendations ar
-- JOIN training_dataset td ON ar.sim_id = td.sim_id;

COMMIT;
